[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "npm", "homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Where to host releases
hosting = "github"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "npm"]
# Homebrew tap to push formula updates to
tap = "AksharP5/homebrew-tap"
# Archive formats for generated bundles
unix-archive = ".tar.gz"
windows-archive = ".zip"
# Release is created by release-plz; dist uploads artifacts to it
create-release = false
# Whether to install an updater program
install-updater = false
