[workspace]
publish = false
git_only = true
changelog_update = true
git_tag_enable = true
git_tag_name = "v{{version}}"
git_release_enable = true
git_release_name = "v{{version}}"
git_release_draft = true
release_always = false
release_commits = "^(feat|fix|perf)(\\(|:)"
